name: "Build and push release image"

on:
  release:
    types:
      - published

jobs:
  push:
    name: push
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v3
     - name: Set up Docker Buildx
       uses: docker/setup-buildx-action@v2

     - name: Login to Docker Hub
       uses: docker/login-action@v2
       with:
         registry: ghcr.io
         username: ${{ github.actor }}
         password: ${{ secrets.GITHUB_TOKEN }}

     - name: Build and push
       uses: docker/build-push-action@v3
       with:
         push: true
         cache-from: type=gha
         cache-to: type=gha,mode=max
         build-args: COMMAFEED_VERSION=${{ github.events.release.name }}
         tags: ghcr.io/jkrafczyk/commafeed-docker:${{ github.events.release.name }}